#!/bin/bash
echo "pos_keys=$(redis-cli KEYS 'quantum:position:BTCUSDT' 'quantum:position:ETHUSDT' 'quantum:position:ADAUSDT' 'quantum:position:SOLUSDT' 'quantum:position:BNBUSDT' 2>/dev/null | wc -l)"
echo "cooldowns=$(redis-cli KEYS 'quantum:cooldown:*' 2>/dev/null | wc -l)"
echo "kelly=$(redis-cli KEYS 'quantum:layer4:sizing:*' 2>/dev/null | wc -l)"
echo "apply-layer=$(systemctl is-active quantum-apply-layer.service 2>/dev/null)"
echo "intent-executor=$(systemctl is-active quantum-intent-executor.service 2>/dev/null)"
echo "BTC_snapshot=$(redis-cli HGET quantum:position:snapshot:BTCUSDT position_amt 2>/dev/null)"
echo "ETH_snapshot=$(redis-cli HGET quantum:position:snapshot:ETHUSDT position_amt 2>/dev/null)"
echo "ADA_snapshot=$(redis-cli HGET quantum:position:snapshot:ADAUSDT position_amt 2>/dev/null)"
echo "SOL_snapshot=$(redis-cli HGET quantum:position:snapshot:SOLUSDT position_amt 2>/dev/null)"
echo "BNB_snapshot=$(redis-cli HGET quantum:position:snapshot:BNBUSDT position_amt 2>/dev/null)"
