#!/bin/bash
echo "=== Checking Redis Signal Storage ==="
echo ""
echo "1. Stream keys:"
redis-cli KEYS "quantum:stream:*"
echo ""
echo "2. Signal keys:"
redis-cli KEYS "*signal*"
echo ""
echo "3. Sample from trade.intent stream (if exists):"
redis-cli XLEN "quantum:stream:trade.intent" 2>/dev/null || echo "Stream does not exist"
echo ""
echo "4. Sample from live_signals key:"
redis-cli GET live_signals | head -c 300
echo ""
