
from typing import Iterator, Any, Optional, List
from datetime import datetime


class TradeLog:
    id: Optional[int]
    timestamp: Optional[datetime]
    symbol: str
    side: str
    qty: float
    price: float
    status: str
    reason: Optional[str]

    def __init__(self, *, symbol: str = ..., side: str = ..., qty: float = ..., price: float = ..., status: str = ..., reason: Optional[str] = ..., timestamp: Optional[datetime] = ..., id: Optional[int] = ...) -> None: ...


class Query:
    def all(self) -> List[Any]: ...

    def first(self) -> Optional[Any]: ...
    def order_by(self, *args: Any) -> 'Query': ...
    def filter(self, *args: Any) -> 'Query': ...
    def limit(self, n: int) -> 'Query': ...
    def offset(self, n: int) -> 'Query': ...


class Session:
    def add(self, obj: Any) -> None: ...

    def commit(self) -> None: ...

    def refresh(self, obj: Any) -> None: ...

    def rollback(self) -> None: ...

    def close(self) -> None: ...

    def cursor(self) -> Any: ...

    def query(self, model: Any) -> Query: ...


def get_db() -> Iterator[Session]: ...


def get_session() -> Session: ...


def create_training_task(db: Session, symbols: str, limit: int): ...


def update_training_task(db: Session, task_id: int, status: str, details: Optional[str] = ...) -> None: ...
