from fastapi import APIRouter
from schemas import AIStatus, PredictionsResponse, Prediction
import time
import random

router = APIRouter(prefix="/ai", tags=["AI"])

@router.get("/status", response_model=AIStatus)
def get_ai_status():
    """Get AI engine status with model performance metrics"""
    return AIStatus(
        accuracy=0.72,
        sharpe=1.14,
        latency=184,
        models=["XGB", "LGBM", "N-HiTS", "TFT"]
    )

@router.get("/predictions", response_model=PredictionsResponse)
def get_ai_predictions():
    """Get latest AI predictions/signals
    
    Returns active trading signals generated by the AI ensemble.
    Mock data - replace with actual prediction service integration.
    """
    # Generate 3-5 mock predictions
    symbols = ["BTCUSDT", "ETHUSDT", "BNBUSDT", "SOLUSDT", "ADAUSDT"]
    models = ["XGB", "LGBM", "N-HiTS", "TFT"]
    regimes = ["Bullish", "Bearish", "Neutral"]
    
    num_predictions = random.randint(3, 5)
    predictions = []
    
    for i in range(num_predictions):
        symbol = random.choice(symbols)
        side = random.choice(["LONG", "SHORT"])
        confidence = round(random.uniform(0.65, 0.95), 2)
        entry_price = round(random.uniform(100, 50000), 2)
        
        predictions.append(Prediction(
            id=f"pred_{int(time.time())}_{i}",
            timestamp=time.strftime("%Y-%m-%d %H:%M:%S"),
            symbol=symbol,
            side=side,
            confidence=confidence,
            entry_price=entry_price,
            stop_loss=round(entry_price * (0.97 if side == "LONG" else 1.03), 2),
            take_profit=round(entry_price * (1.05 if side == "LONG" else 0.95), 2),
            leverage=random.choice([5, 10, 15, 20]),
            model=random.choice(models),
            reason=f"Strong {'bullish' if side == 'LONG' else 'bearish'} signal from {random.choice(models)}",
            volatility=round(random.uniform(0.015, 0.035), 3),
            regime=random.choice(regimes),
            position_size_usd=round(random.uniform(500, 2000), 2)
        ))
    
    return PredictionsResponse(
        predictions=predictions,
        count=len(predictions),
        timestamp=time.time()
    )
