"""
Signal Domain Models
EPIC: DASHBOARD-V3-TRADING-PANELS

Defines signal record structure for dashboard display.
"""

from typing import Optional
from datetime import datetime
from pydantic import BaseModel, Field


class SignalRecord(BaseModel):
    """
    AI signal record for dashboard display.
    
    Represents trading signals generated by AI models.
    """
    id: str = Field(description="Signal ID")
    timestamp: datetime = Field(description="Signal generation time")
    account: Optional[str] = Field(default=None, description="Target account")
    symbol: str = Field(description="Trading symbol")
    direction: str = Field(description="LONG or SHORT (or BUY/SELL)")
    confidence: float = Field(ge=0.0, le=1.0, description="Confidence score (0-1)")
    strategy_id: Optional[str] = Field(default=None, description="Strategy identifier")
    price: Optional[float] = Field(default=None, description="Signal price")
    source: Optional[str] = Field(default="AI", description="Signal source")
    
    class Config:
        json_encoders = {
            datetime: lambda v: v.isoformat()
        }
