"""autogen

Revision ID: 22e8fe9ca789
Revises: 0001_initial
Create Date: 2025-09-24 02:57:47.830324
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '22e8fe9ca789'
down_revision = '0001_initial'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
