name: Auto-fix on failed workflow

on:
  workflow_run:
    types: [completed]

jobs:
  auto-fix:
    if: github.event.workflow_run.conclusion == 'failure' && contains(github.event.workflow_run.pull_requests, 0)
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dev dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f backend/requirements-dev.txt ]; then python -m pip install -r backend/requirements-dev.txt; fi
          python -m pip install pre-commit ruff mypy

      - name: Run auto-fix script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          chmod +x .github/auto-fix/auto_fix.sh
          .github/auto-fix/auto_fix.sh
