name: CI - Quantum Trader

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: quantum
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install pip + deps
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install ruff mypy black pytest coverage bandit safety sqlalchemy-utils

      # --- Linting ---
      - name: Run Ruff
        run: ruff check backend

      - name: Run Mypy
        run: mypy backend

      - name: Run Black
        run: black --check backend

      # --- Security ---
      - name: Run Bandit
        # Tests frequently use plain `assert` statements; exclude test files from Bandit
        # scanning to avoid low-severity B101 findings failing CI. We still scan
        # application code under backend/ for security issues.
        run: bandit -r backend --exclude backend/tests

      - name: Run Safety
        run: safety check

      # --- Tests ---
      - name: Run Pytest with Coverage
        env:
          ENV: test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: quantum
          POSTGRES_HOST: localhost
        run: |
          coverage run -m pytest backend/tests
          coverage report -m
