name: CI - Quantum Trader

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: quantum
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install pip + deps
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          # Install linters/test tools explicitly; avoid installing the full
          # backend/requirements-dev.txt so dev-only deps (e.g. SQLAlchemy-Utils)
          # are not installed in CI runtime. This keeps the runtime surface
          # minimal and ensures advisories are surfaced and tracked.
          pip install ruff mypy black pytest coverage bandit safety pytest-asyncio httpx anyio

      # --- Linting ---
      - name: Run Ruff
        run: ruff check backend

      - name: Run Mypy
        run: mypy backend

      - name: Run Black
        run: black --check backend

      # --- Security ---
      - name: Run Bandit
        # Tests frequently use plain `assert` statements; exclude test files from Bandit
        # scanning to avoid low-severity B101 findings failing CI. We still scan
        # application code under backend/ for security issues.
        run: bandit -r backend --exclude backend/tests

      - name: Run Safety
        run: safety check

      - name: Check for dev-only packages in runtime (FAILS if any found)
        if: github.event_name == 'pull_request' || github.ref == 'refs/heads/main'
        run: |
          python backend/scripts/check_dev_deps_in_runtime.py

      # --- Tests ---
      - name: Run Pytest with Coverage
        env:
          ENV: test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: quantum
          POSTGRES_HOST: localhost
        run: |
          coverage run -m pytest backend/tests
          coverage report -m
