name: Dev tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ fix/precommit-patches-from-main ]

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - name: Set up Python
        uses: actions/setup-python@v5.2.0
        with:
          python-version: '3.11'
      - name: Install backend dev requirements
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r backend/requirements-dev.txt
      - name: Run pytest
        run: python -m pytest -q
