name: Frontend Docker Test

on:
  workflow_dispatch:

jobs:
  frontend-docker-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.6.1
      - name: Build and run frontend test image
        run: |
          docker build -f frontend/Dockerfile.test -t qt-frontend-test:latest frontend
          docker run --rm qt-frontend-test:latest
