name: Test PAT Secret

on:
  workflow_dispatch: {}
  push:
    branches:
      - chore/mypy-fixes

jobs:
  test-pat:
    runs-on: ubuntu-latest
    steps:
      - name: Show runner info
        run: |
          echo "Runner: $RUNNER_OS"
          echo "Repo: $GITHUB_REPOSITORY"

      - name: Test MY_PAT by calling GitHub API
        env:
          MY_PAT: ${{ secrets.MY_PAT }}
        run: |
          echo "Calling GitHub API as secret owner (login will be printed masked)"
          curl -sS -H "Authorization: token $MY_PAT" https://api.github.com/user | python -c "import sys,json;print(json.load(sys.stdin).get('login'))"
